# Generated by Django 4.0.2 on 2022-02-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_cv_pdf_resume_cv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at']},
        ),
    ]
