# Generated by Django 4.0.2 on 2022-02-25 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_certificates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Certificate',
        ),
    ]
