# Generated by Django 4.0.2 on 2022-02-25 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_resume_certificates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='certificates',
        ),
    ]
